const SERVICE_NAME = "kumir-directory";
const SERVICE_ACTIONS = Object.freeze(["users.search"]);

const APP_VERSION = "5.3.0";
const DB_IDS = Object.freeze({
  AUTH: "1T5iqlQSxoGIBSA8t-GCeYWNtgKGEL7Qh6prZyfVOBOc",
  MESSAGES: "1teFreIz4rul32y3dUi35diDcwtcR8Kyiat7eMxCjOt4",
  CONVERSATIONS: "1T-HUwZhWx2S60vlBftEb6c2ms9yglO2GWxH55LQM51g",
  PROFILES: "1xHTuClBKGCbavgzSLgdmQtqMJ_EcFVX6i_byZrc_334"
});
const HEADERS = Object.freeze({
  Users:["user_id","username_key","password_hash","password_salt","password_version","status","created_at","updated_at","last_login_at"],
  Sessions:["session_id_hash","user_id","device_id","created_at","expires_at","revoked_at"],
  Profiles:["user_id","display_name","phone","bio","current_photo_id","created_at","updated_at"],
  ProfilePhotos:["photo_id","user_id","storage_file_id","mime_type","size_bytes","sha256","position","created_at","deleted_at"],
  Conversations:["conversation_id","type","dm_key","title","username_key","photo_id","owner_user_id","status","last_message_seq","last_message_at","created_at","updated_at"],
  ConversationMembers:["conversation_id","user_id","role","joined_at","left_at","last_read_seq","cleared_before_seq","muted_until","status"],
  Messages:["message_id","conversation_id","seq","sender_user_id","kind","text","reply_to_message_id","forwarded_from_message_id","created_at","edited_at","deleted_at","expires_at"],
  MessageMedia:["media_id","message_id","storage_file_id","original_name","mime_type","size_bytes","sha256","created_at","expires_at","deleted_at"],
  MessageReactions:["conversation_id","message_id","user_id","emoji","created_at"],
  RetentionQueue:["queue_id","entity_type","entity_id","conversation_id","storage_file_id","expires_at","status","attempts","next_attempt_at","last_error","created_at","processed_at"]
});
const SESSION_TTL_MS=180*86400000, MESSAGE_TTL_MS=10*86400000;
const MEDIA_CHUNK_BYTES=2*1024*1024, MEDIA_MAX_BYTES=1024*1024*1024;

let REQUEST_CACHE_={books:{},sheets:{},rows:{},headers:{},directory:null};
function beginRequest_(){REQUEST_CACHE_={books:{},sheets:{},rows:{},headers:{},directory:null};}
function doGet(){beginRequest_();return out_({ok:true,service:typeof SERVICE_NAME!=="undefined"?SERVICE_NAME:"messenger-backend",version:APP_VERSION,serverTime:now_()});}
function doPost(e){
  beginRequest_();
  const requestId=Utilities.getUuid();
  try{
    const r=JSON.parse(e&&e.postData&&e.postData.contents||"{}");
    const result=route_(alias_(r.action),r.payload||{}); result.request_id=requestId; return out_(result);
  }catch(error){console.error(error);return out_({ok:false,request_id:requestId,code:error.code||"SERVER_ERROR",error:error.message||"Ошибка сервера"});}
}
function route_(action,p){
  if(typeof SERVICE_ACTIONS!=="undefined"&&SERVICE_ACTIONS.indexOf(action)<0&&action!=="health")fail_("WRONG_SERVICE","Команда не относится к этому сервису");
  const routes={
    "auth.register":register_,"auth.login":login_,"auth.logout":logout_,"auth.me":me_,
    "users.search":searchUsers_,"profile.get":profileGet_,"profile.update":profileUpdate_,"profile.photo.set":profilePhotoSet_,"profile.photo.get":profilePhotoGet_,
    "conversations.list":conversationsList_,"conversations.ensureDm":ensureDm_,"conversations.clearForMe":clearForMe_,"conversations.read":conversationRead_,
    "spaces.create":spaceCreate_,"spaces.update":spaceUpdate_,"spaces.leave":spaceLeave_,"spaces.members.setRole":memberRole_,
    "messages.page":messagesPage_,"messages.sync":messagesSync_,"sync.bundle":syncBundle_,"messages.send":messageSend_,"messages.edit":messageEdit_,"messages.delete":messageDelete_,"reactions.toggle":reactionToggle_,
    "media.init":mediaInit_,"media.putChunk":mediaPutChunk_,"media.complete":mediaComplete_,"media.downloadChunk":mediaDownloadChunk_,
    health:function(){return {ok:true,version:APP_VERSION,serverTime:now_()};}
  };
  if(!routes[action]) fail_("UNKNOWN_ACTION","Неизвестная команда"); return routes[action](p)||{ok:true};
}
function alias_(a){return ({register:"auth.register",login:"auth.login",logout:"auth.logout",me:"auth.me",searchUsers:"users.search",getUserChats:"conversations.list",getMessages:"messages.page",send:"messages.send",sync:"messages.sync"})[a]||String(a||"");}
function out_(v){return ContentService.createTextOutput(JSON.stringify(v)).setMimeType(ContentService.MimeType.JSON);}
function fail_(c,m){const e=new Error(m);e.code=c;throw e;}
function now_(){return new Date().toISOString();}
function id_(p){return p+"_"+Utilities.getUuid().replace(/-/g,"");}
function db_(k){if(!REQUEST_CACHE_.books)beginRequest_();return REQUEST_CACHE_.books[k]||(REQUEST_CACHE_.books[k]=SpreadsheetApp.openById(DB_IDS[k]));}
function msgSheetName_(d){return "Messages_"+Utilities.formatDate(d||new Date(),"UTC","yyyy_MM");}
function sheet_(dbKey,name,headers){const key=dbKey+":"+name;if(REQUEST_CACHE_.sheets[key])return REQUEST_CACHE_.sheets[key];const book=db_(dbKey);let s=book.getSheetByName(name);if(!s)s=ensureSheet_(book,name,headers||HEADERS[name]);REQUEST_CACHE_.sheets[key]=s;return s;}
function ensureSheet_(book,name,headers){
  let s=book.getSheetByName(name);if(!s)s=book.insertSheet(name);
  const existing=s.getRange(1,1,1,headers.length).getValues()[0].map(String);
  if(s.getLastRow()<=1&&!headers.every((h,i)=>existing[i]===h))s.getRange(1,1,1,headers.length).setValues([headers]);
  else if(!headers.every((h,i)=>existing[i]===h))fail_("SCHEMA_ERROR","Неверная схема листа "+name);
  s.setFrozenRows(1);s.getRange(1,1,1,headers.length).setFontWeight("bold").setBackground("#172033").setFontColor("#ffffff");return s;
}
function sheetCacheKey_(s){return String(s.getParent().getId())+":"+String(s.getSheetId());}
function headers_(s){const key=sheetCacheKey_(s);if(REQUEST_CACHE_.headers[key])return REQUEST_CACHE_.headers[key];const lc=s.getLastColumn(),h=lc?s.getRange(1,1,1,lc).getValues()[0].map(String):[];REQUEST_CACHE_.headers[key]=h;return h;}
function invalidate_(s){const key=sheetCacheKey_(s);delete REQUEST_CACHE_.rows[key];delete REQUEST_CACHE_.headers[key];REQUEST_CACHE_.directory=null;}
function objects_(s){const key=sheetCacheKey_(s);if(REQUEST_CACHE_.rows[key])return REQUEST_CACHE_.rows[key];const lr=s.getLastRow(),h=headers_(s);if(lr<2)return(REQUEST_CACHE_.rows[key]=[]);const rows=s.getRange(2,1,lr-1,h.length).getValues().map((v,i)=>{const o={_row:i+2};h.forEach((x,j)=>o[x]=v[j]);return o;});REQUEST_CACHE_.rows[key]=rows;return rows;}
function find_(s,key,value,predicate){const target=String(value);return objects_(s).find(o=>String(o[key])===target&&(!predicate||predicate(o)))||null;}
function append_(s,o){const h=headers_(s);s.appendRow(h.map(k=>o[k]==null?"":o[k]));invalidate_(s);return o;}
function patch_(s,row,p){const h=headers_(s),v=s.getRange(row,1,1,h.length).getValues()[0];h.forEach((k,i)=>{if(Object.prototype.hasOwnProperty.call(p,k))v[i]=p[k];});s.getRange(row,1,1,h.length).setValues([v]);invalidate_(s);}
function locked_(fn){const l=LockService.getScriptLock();l.waitLock(20000);try{return fn();}finally{l.releaseLock();}}
function cleanUser_(v){const u=String(v||"").trim().replace(/^@/,"").toLowerCase();if(!/^[a-z][a-z0-9_]{2,31}$/.test(u))fail_("INVALID_USERNAME","Username: 3–32 символа, латинская буква в начале");return u;}
function cleanPassword_(v){const p=String(v||"");if(p.length<4||p.length>256)fail_("INVALID_PASSWORD","Пароль должен содержать от 4 до 256 символов");return p;}
function cleanText_(v,n){const x=String(v==null?"":v).trim();if(x.length>n)fail_("TEXT_TOO_LONG","Слишком длинный текст");return x;}
function hex_(bytes){return bytes.map(x=>(x<0?x+256:x).toString(16).padStart(2,"0")).join("");}
function sha_(v){return hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(v),Utilities.Charset.UTF_8));}
function pepper_(){const p=PropertiesService.getScriptProperties();let x=p.getProperty("AUTH_PEPPER");if(!x){x=Utilities.getUuid()+Utilities.getUuid();p.setProperty("AUTH_PEPPER",x);}return x;}
function passwordHashV1_(password,salt){let x=pepper_()+":"+salt+":"+password;for(let i=0;i<1200;i++)x=sha_(x+":"+i);return x;}
function passwordHash_(password,salt){return hex_(Utilities.computeHmacSha256Signature(String(salt)+":"+String(password),pepper_(),Utilities.Charset.UTF_8));}
function constant_(a,b){a=String(a);b=String(b);if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}

function setupProject(){
  ensureSheet_(db_("AUTH"),"Users",HEADERS.Users);ensureSheet_(db_("AUTH"),"Sessions",HEADERS.Sessions);
  ensureSheet_(db_("PROFILES"),"Profiles",HEADERS.Profiles);ensureSheet_(db_("PROFILES"),"ProfilePhotos",HEADERS.ProfilePhotos);
  ensureSheet_(db_("CONVERSATIONS"),"Conversations",HEADERS.Conversations);ensureSheet_(db_("CONVERSATIONS"),"ConversationMembers",HEADERS.ConversationMembers);
  ensureSheet_(db_("MESSAGES"),msgSheetName_(new Date()),HEADERS.Messages);ensureSheet_(db_("MESSAGES"),"MessageMedia",HEADERS.MessageMedia);ensureSheet_(db_("MESSAGES"),"MessageReactions",HEADERS.MessageReactions);ensureSheet_(db_("MESSAGES"),"RetentionQueue",HEADERS.RetentionQueue);
  pepper_();const props=PropertiesService.getScriptProperties();if(!props.getProperty("MEDIA_ROOT_FOLDER_ID"))props.setProperty("MEDIA_ROOT_FOLDER_ID",DriveApp.createFolder("Messenger Private Media").getId());
  if(!ScriptApp.getProjectTriggers().some(t=>t.getHandlerFunction()==="runDailyRetention"))ScriptApp.newTrigger("runDailyRetention").timeBased().atHour(0).everyDays(1).inTimezone("Europe/Moscow").create();
  return{ok:true,version:APP_VERSION,databaseIds:DB_IDS};
}

function register_(p){return locked_(()=>{const username=cleanUser_(p.username),password=cleanPassword_(p.password),users=sheet_("AUTH","Users");if(find_(users,"username_key",username))fail_("USERNAME_TAKEN","Этот username уже занят");const at=now_(),userId=id_("usr"),salt=id_("salt");append_(users,{user_id:userId,username_key:username,password_hash:passwordHash_(password,salt),password_salt:salt,password_version:"v2",status:"active",created_at:at,updated_at:at,last_login_at:""});return{ok:true,user:{id:userId,userId:userId,username:username,name:"@"+username,displayName:"@"+username,phone:"",bio:"",photoId:""}};});}
function login_(p){const username=cleanUser_(p.username),password=cleanPassword_(p.password),users=sheet_("AUTH","Users"),u=find_(users,"username_key",username,o=>String(o.status)==="active"),version=String(u&&u.password_version||"v1"),hash=u&&(version==="v2"?passwordHash_(password,String(u.password_salt)):passwordHashV1_(password,String(u.password_salt)));if(!u||!constant_(u.password_hash,hash))fail_("INVALID_CREDENTIALS","Неверный username или пароль");if(version!=="v2")patch_(users,u._row,{password_hash:passwordHash_(password,String(u.password_salt)),password_version:"v2",last_login_at:now_(),updated_at:now_()});else patch_(users,u._row,{last_login_at:now_(),updated_at:now_()});const userId=String(u.user_id);return{ok:true,user:{id:userId,userId:userId,username:username,name:"@"+username,displayName:"@"+username,phone:"",bio:"",photoId:""},session:issueSession_(userId,p.deviceId)};}
function issueSession_(userId,deviceId){const raw=id_("ses")+Utilities.getUuid().replace(/-/g,""),at=now_(),expires=new Date(Date.now()+SESSION_TTL_MS).toISOString();append_(sheet_("AUTH","Sessions"),{session_id_hash:sha_(raw),user_id:userId,device_id:String(deviceId||"web"),created_at:at,expires_at:expires,revoked_at:""});return{token:raw,expiresAt:expires};}
function auth_(token){if(!token)fail_("AUTH_REQUIRED","Требуется вход");const sessions=sheet_("AUTH","Sessions"),s=find_(sessions,"session_id_hash",sha_(token),o=>!o.revoked_at&&new Date(o.expires_at).getTime()>Date.now());if(!s)fail_("SESSION_EXPIRED","Сессия недействительна");const user=find_(sheet_("AUTH","Users"),"user_id",s.user_id,o=>String(o.status)==="active");if(!user)fail_("AUTH_REQUIRED","Пользователь недоступен");return{userId:String(user.user_id),user:user,session:s,sessions:sessions};}
function logout_(p){const a=auth_(p.sessionToken);patch_(a.sessions,a.session._row,{revoked_at:now_()});return{ok:true};}
function me_(p){const a=auth_(p.sessionToken);return{ok:true,user:publicUser_(a.userId)};}
function directory_(){if(REQUEST_CACHE_.directory)return REQUEST_CACHE_.directory;const users={},profiles={};objects_(sheet_("AUTH","Users")).forEach(x=>users[String(x.user_id)]=x);objects_(sheet_("PROFILES","Profiles")).forEach(x=>profiles[String(x.user_id)]=x);return(REQUEST_CACHE_.directory={users:users,profiles:profiles});}
function ensureProfile_(userId){const profiles=sheet_("PROFILES","Profiles"),existing=find_(profiles,"user_id",userId);if(existing)return existing;const user=find_(sheet_("AUTH","Users"),"user_id",userId),at=now_();return locked_(()=>find_(profiles,"user_id",userId)||append_(profiles,{user_id:userId,display_name:"@"+String(user&&user.username_key||"user"),phone:"",bio:"",current_photo_id:"",created_at:at,updated_at:at}));}
function publicUser_(userId){const d=directory_(),u=d.users[String(userId)],profile=d.profiles[String(userId)];return{id:userId,userId:userId,username:String(u&&u.username_key||""),name:String(profile&&profile.display_name||"@"+(u&&u.username_key||"")),displayName:String(profile&&profile.display_name||""),phone:String(profile&&profile.phone||""),bio:String(profile&&profile.bio||""),photoId:String(profile&&profile.current_photo_id||"")};}
function searchUsers_(p){const a=auth_(p.sessionToken),q=String(p.query||"").trim().replace(/^@/,"").toLowerCase();if(!q)return{ok:true,users:[]};const users=objects_(sheet_("AUTH","Users")).filter(u=>String(u.status)==="active"&&String(u.user_id)!==a.userId&&String(u.username_key).indexOf(q)>=0).slice(0,30).map(u=>publicUser_(String(u.user_id)));return{ok:true,users:users};}
function profileGet_(p){const a=auth_(p.sessionToken);let userId=String(p.userId||"");if(!userId&&p.username){const u=find_(sheet_("AUTH","Users"),"username_key",String(p.username).replace(/^@/,"").toLowerCase());userId=u&&String(u.user_id)||"";}if(!userId)userId=a.userId;if(userId===a.userId)ensureProfile_(userId);return{ok:true,user:publicUser_(userId)};}
function profileUpdate_(p){const a=auth_(p.sessionToken),s=sheet_("PROFILES","Profiles"),r=ensureProfile_(a.userId),patch={updated_at:now_()};if(p.displayName!==undefined)patch.display_name=cleanText_(p.displayName,64);if(p.phone!==undefined)patch.phone=cleanText_(p.phone,32);if(p.bio!==undefined)patch.bio=cleanText_(p.bio,500);if(p.photoId!==undefined)patch.current_photo_id=String(p.photoId||"");patch_(s,r._row,patch);return{ok:true,user:publicUser_(a.userId)};}
function profilePhotoSet_(p){const a=auth_(p.sessionToken),match=String(p.dataUrl||"").match(/^data:([^;,]+);base64,(.+)$/);if(!match)fail_("INVALID_PHOTO","Некорректная фотография");const bytes=Utilities.base64Decode(match[2]);if(bytes.length>5*1024*1024)fail_("PHOTO_TOO_LARGE","Фотография слишком большая");const photoId=id_("photo"),file=mediaRoot_().createFile(Utilities.newBlob(bytes,match[1],photoId)),at=now_(),photos=sheet_("PROFILES","ProfilePhotos");objects_(photos).filter(x=>String(x.user_id)===a.userId&&!x.deleted_at).forEach(x=>patch_(photos,x._row,{position:Number(x.position||0)+1}));append_(photos,{photo_id:photoId,user_id:a.userId,storage_file_id:file.getId(),mime_type:match[1],size_bytes:bytes.length,sha256:hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,bytes)),position:0,created_at:at,deleted_at:""});const profiles=sheet_("PROFILES","Profiles"),profile=find_(profiles,"user_id",a.userId);patch_(profiles,profile._row,{current_photo_id:photoId,updated_at:at});return{ok:true,user:publicUser_(a.userId),photoId:photoId};}
function profilePhotoGet_(p){const a=auth_(p.sessionToken),userId=String(p.userId||"");let target=userId;if(!target&&p.username){const u=find_(sheet_("AUTH","Users"),"username_key",String(p.username).replace(/^@/,"").toLowerCase());target=u&&String(u.user_id)||"";}if(!target)target=a.userId;const profile=find_(sheet_("PROFILES","Profiles"),"user_id",target),photoId=String(p.photoId||(profile&&profile.current_photo_id)||"");if(!photoId)return{ok:true,photoId:"",dataUrl:""};const photo=find_(sheet_("PROFILES","ProfilePhotos"),"photo_id",photoId,o=>String(o.user_id)===target&&!o.deleted_at);if(!photo)return{ok:true,photoId:"",dataUrl:""};const blob=DriveApp.getFileById(String(photo.storage_file_id)).getBlob();return{ok:true,photoId:photoId,dataUrl:"data:"+String(photo.mime_type||blob.getContentType()||"image/jpeg")+";base64,"+Utilities.base64Encode(blob.getBytes())};}

function createConversation_(type,dmKey,title,username,owner,members){const at=now_(),id=id_("conv"),c=sheet_("CONVERSATIONS","Conversations"),m=sheet_("CONVERSATIONS","ConversationMembers");append_(c,{conversation_id:id,type:type,dm_key:dmKey,title:title,username_key:username,photo_id:"",owner_user_id:owner,status:"active",last_message_seq:0,last_message_at:"",created_at:at,updated_at:at});members.forEach(x=>append_(m,{conversation_id:id,user_id:x.userId,role:x.role,joined_at:at,left_at:"",last_read_seq:0,cleared_before_seq:0,muted_until:"",status:"active"}));return find_(c,"conversation_id",id);}
function membership_(conversationId,userId){return find_(sheet_("CONVERSATIONS","ConversationMembers"),"conversation_id",conversationId,o=>String(o.user_id)===String(userId)&&String(o.status)==="active");}
function requireMember_(conversationId,userId){const c=find_(sheet_("CONVERSATIONS","Conversations"),"conversation_id",conversationId,o=>String(o.status)==="active");if(!c)fail_("CHAT_NOT_FOUND","Переписка не найдена");const m=membership_(conversationId,userId);if(!m)fail_("CHAT_ACCESS_DENIED","Нет доступа к переписке");return{conversation:c,member:m};}
function ensureDm_(p){const a=auth_(p.sessionToken),users=sheet_("AUTH","Users"),peer=find_(users,"username_key",cleanUser_(p.username),o=>String(o.status)==="active");if(!peer)fail_("USER_NOT_FOUND","Пользователь не найден");const ids=[a.userId,String(peer.user_id)].sort(),key=ids.join(":"),c=sheet_("CONVERSATIONS","Conversations");let chat=find_(c,"dm_key",key,o=>String(o.status)==="active");if(!chat)chat=locked_(()=>find_(c,"dm_key",key,o=>String(o.status)==="active")||createConversation_("dm",key,"","",a.userId,[{userId:ids[0],role:"member"},{userId:ids[1],role:"member"}]));return{ok:true,conversation:conversationPublic_(chat,a.userId)};}
function conversationContext_(){const byConversation={};objects_(sheet_("CONVERSATIONS","ConversationMembers")).forEach(m=>{const id=String(m.conversation_id);(byConversation[id]||(byConversation[id]=[])).push(m);});return{membersByConversation:byConversation};}
function conversationPublic_(c,userId,ctx){ctx=ctx||conversationContext_();const o={id:String(c.conversation_id),conversationId:String(c.conversation_id),type:String(c.type),title:String(c.title||""),username:String(c.username_key||""),photoId:String(c.photo_id||""),lastMessageSeq:Number(c.last_message_seq)||0,lastMessageAt:String(c.last_message_at||""),timestamp:c.last_message_at?new Date(c.last_message_at).getTime():new Date(c.created_at).getTime(),isSaved:String(c.type)==="saved",isGroup:String(c.type)==="group",isChannel:String(c.type)==="channel",isCommunity:["group","channel"].includes(String(c.type))};const members=(ctx.membersByConversation[o.id]||[]).filter(m=>String(m.status)==="active"),mine=members.find(m=>String(m.user_id)===String(userId));o.unreadCount=Math.max(0,o.lastMessageSeq-Number(mine&&mine.last_read_seq||0));if(String(c.type)==="dm"){const peerId=String(c.dm_key).split(":").find(x=>x!==String(userId));const peer=publicUser_(peerId);o.peer=peer.username;o.targetUser=peer.username;o.title=peer.name;o.avatar=peer.photoId||"";}if(o.isCommunity){o.memberCount=members.length;o.currentRole=String(mine&&mine.role||"");o.members=members.map(m=>publicUser_(String(m.user_id)).username).filter(Boolean);o.admins=members.filter(m=>["owner","admin"].includes(String(m.role))).map(m=>publicUser_(String(m.user_id)).username).filter(Boolean);o.owner=publicUser_(String(c.owner_user_id)).username;}if(o.isSaved)o.title="Избранное";return o;}
function conversationsListCore_(a){let ctx=conversationContext_(),memberRows=(ctx.membersByConversation||{}),allowed={};Object.keys(memberRows).forEach(id=>{if(memberRows[id].some(m=>String(m.user_id)===a.userId&&String(m.status)==="active"))allowed[id]=true;});let rows=objects_(sheet_("CONVERSATIONS","Conversations")).filter(c=>allowed[String(c.conversation_id)]&&String(c.status)==="active");if(!rows.some(c=>String(c.type)==="saved")){locked_(()=>{const fresh=objects_(sheet_("CONVERSATIONS","ConversationMembers")).filter(m=>String(m.user_id)===a.userId&&String(m.status)==="active").map(m=>String(m.conversation_id)),exists=objects_(sheet_("CONVERSATIONS","Conversations")).some(c=>fresh.indexOf(String(c.conversation_id))>=0&&String(c.type)==="saved"&&String(c.status)==="active");if(!exists)createConversation_("saved","","Избранное","",a.userId,[{userId:a.userId,role:"owner"}]);});ctx=conversationContext_();return conversationsListCore_(a);}return rows.map(c=>conversationPublic_(c,a.userId,ctx)).sort((x,y)=>y.timestamp-x.timestamp);}
function conversationsList_(p){const a=auth_(p.sessionToken),rows=conversationsListCore_(a);return{ok:true,conversations:rows,chats:rows};}
function spaceCreate_(p){const a=auth_(p.sessionToken),type=p.type==="channel"?"channel":"group",title=cleanText_(p.title,100),username=cleanUser_(p.username),convos=sheet_("CONVERSATIONS","Conversations");if(find_(convos,"username_key",username,o=>String(o.status)==="active"))fail_("USERNAME_TAKEN","Этот username уже занят");const memberIds=[a.userId];(p.members||[]).forEach(name=>{const u=find_(sheet_("AUTH","Users"),"username_key",String(name).replace(/^@/,"").toLowerCase());if(u&&!memberIds.includes(String(u.user_id)))memberIds.push(String(u.user_id));});const c=locked_(()=>createConversation_(type,"",title,username,a.userId,memberIds.map(x=>({userId:x,role:x===a.userId?"owner":(type==="channel"?"subscriber":"member")}))));return{ok:true,conversation:conversationPublic_(c,a.userId)};}
function spaceUpdate_(p){const a=auth_(p.sessionToken),x=requireMember_(String(p.conversationId),a.userId);if(!["owner","admin"].includes(String(x.member.role)))fail_("FORBIDDEN","Недостаточно прав");const change={updated_at:now_()};if(p.title!==undefined)change.title=cleanText_(p.title,100);if(p.username!==undefined)change.username_key=cleanUser_(p.username);if(p.photoId!==undefined)change.photo_id=String(p.photoId||"");patch_(sheet_("CONVERSATIONS","Conversations"),x.conversation._row,change);return{ok:true};}
function memberRole_(p){const a=auth_(p.sessionToken),x=requireMember_(String(p.conversationId),a.userId);if(String(x.member.role)!=="owner")fail_("FORBIDDEN","Только владелец меняет роли");const row=find_(sheet_("CONVERSATIONS","ConversationMembers"),"conversation_id",p.conversationId,o=>String(o.user_id)===String(p.userId)&&String(o.status)==="active");if(!row)fail_("USER_NOT_FOUND","Участник не найден");patch_(sheet_("CONVERSATIONS","ConversationMembers"),row._row,{role:String(p.role||"member")});return{ok:true};}
function spaceLeave_(p){const a=auth_(p.sessionToken),cid=String(p.conversationId),x=requireMember_(cid,a.userId),members=sheet_("CONVERSATIONS","ConversationMembers"),conversations=sheet_("CONVERSATIONS","Conversations");patch_(members,x.member._row,{status:"left",left_at:now_()});const active=objects_(members).filter(m=>String(m.conversation_id)===cid&&String(m.status)==="active");if(!active.length&&["group","channel"].includes(String(x.conversation.type))){patch_(conversations,x.conversation._row,{status:"deleted",updated_at:now_()});append_(sheet_("MESSAGES","RetentionQueue"),{queue_id:id_("queue"),entity_type:"conversation",entity_id:cid,conversation_id:cid,storage_file_id:"",expires_at:now_(),status:"pending",attempts:0,next_attempt_at:now_(),last_error:"",created_at:now_(),processed_at:""});}else if(String(x.member.role)==="owner"){const next=active[0];patch_(members,next._row,{role:"owner"});patch_(conversations,x.conversation._row,{owner_user_id:String(next.user_id),updated_at:now_()});}return{ok:true,deleted:!active.length};}
function clearForMe_(p){const a=auth_(p.sessionToken),x=requireMember_(String(p.conversationId),a.userId);patch_(sheet_("CONVERSATIONS","ConversationMembers"),x.member._row,{cleared_before_seq:Number(x.conversation.last_message_seq)||0});return{ok:true};}
function conversationRead_(p){const a=auth_(p.sessionToken),cid=String(p.conversationId||p.chatId||""),x=requireMember_(cid,a.userId),seq=Math.min(Number(p.seq)||Number(x.conversation.last_message_seq)||0,Number(x.conversation.last_message_seq)||0),current=Number(x.member.last_read_seq)||0;if(seq>current)patch_(sheet_("CONVERSATIONS","ConversationMembers"),x.member._row,{last_read_seq:seq});return{ok:true,conversationId:cid,lastReadSeq:Math.max(current,seq)};}

function candidateMessageSheets_(){if(REQUEST_CACHE_.messageSheets)return REQUEST_CACHE_.messageSheets;const book=db_("MESSAGES"),dates=[new Date(),new Date(Date.now()-31*86400000)];return(REQUEST_CACHE_.messageSheets=dates.map(d=>book.getSheetByName(msgSheetName_(d))).filter((s,i,a)=>s&&a.indexOf(s)===i));}
function messageById_(cid,mid){for(const s of candidateMessageSheets_()){const r=find_(s,"message_id",mid,o=>String(o.conversation_id)===cid);if(r)return{sheet:s,row:r};}return null;}
function messageContext_(){const media={},reactions={};objects_(sheet_("MESSAGES","MessageMedia")).forEach(x=>{if(!x.deleted_at){const id=String(x.message_id);if(id)(media[id]||(media[id]=[])).push(x);}});objects_(sheet_("MESSAGES","MessageReactions")).forEach(x=>{const id=String(x.message_id);(reactions[id]||(reactions[id]=[])).push(x);});const conversation=conversationContext_();return{mediaByMessage:media,reactionsByMessage:reactions,membersByConversation:conversation.membersByConversation};}
function messagePublic_(m,ctx){ctx=ctx||messageContext_();const mid=String(m.message_id),cid=String(m.conversation_id),seq=Number(m.seq)||0,senderId=String(m.sender_user_id),sender=publicUser_(senderId),media=(ctx.mediaByMessage[mid]||[]).map(x=>({mediaId:String(x.media_id),name:String(x.original_name),type:String(x.mime_type),size:Number(x.size_bytes)||0,sha256:String(x.sha256),chunked:true})),reactions={};(ctx.reactionsByMessage[mid]||[]).filter(x=>String(x.conversation_id)===cid).forEach(x=>{const emoji=String(x.emoji);if(!reactions[emoji])reactions[emoji]=[];reactions[emoji].push(publicUser_(String(x.user_id)).username);});const members=(ctx.membersByConversation[cid]||[]).filter(x=>String(x.status)==="active"&&String(x.user_id)!==senderId),isSaved=!members.length,read=isSaved||members.some(x=>Number(x.last_read_seq||0)>=seq);return{id:mid,messageId:mid,chatId:cid,conversationId:cid,seq:seq,sender:sender.username,senderUserId:sender.userId,text:String(m.text||""),kind:String(m.kind||"text"),files:media,file:media[0]||null,reactions:reactions,deliveryStatus:read?"read":"delivered",replyToMessageId:String(m.reply_to_message_id||""),createdAt:new Date(m.created_at).getTime(),editedAt:m.edited_at?new Date(m.edited_at).getTime():0,time:Utilities.formatDate(new Date(m.created_at),"Europe/Moscow","HH:mm")};}
function messagesPageCore_(a,p){const cid=String(p.conversationId||p.chatId||""),x=requireMember_(cid,a.userId),before=Number(p.beforeSeq)||Infinity,limit=Math.min(Math.max(Number(p.limit)||100,1),200),cutoff=Date.now()-MESSAGE_TTL_MS,rows=[];candidateMessageSheets_().forEach(s=>objects_(s).forEach(m=>{if(String(m.conversation_id)===cid&&!m.deleted_at&&new Date(m.created_at).getTime()>=cutoff&&Number(m.seq)<before&&Number(m.seq)>Number(x.member.cleared_before_seq||0))rows.push(m);}));rows.sort((q,w)=>Number(q.seq)-Number(w.seq));const ctx=messageContext_(),page=rows.slice(-limit).map(m=>messagePublic_(m,ctx));return{conversationId:cid,messages:page,nextBeforeSeq:page.length?Number(page[0].seq):null};}
function messagesPage_(p){const a=auth_(p.sessionToken),result=messagesPageCore_(a,p);result.ok=true;return result;}
function messagesSync_(p){const result=messagesPage_(Object.assign({},p,{beforeSeq:0,limit:200})),after=Number(p.afterSeq)||0;result.messages=result.messages.filter(m=>m.seq>after);return result;}
function syncBundle_(p){const a=auth_(p.sessionToken),conversations=conversationsListCore_(a),messages=p.conversationId?messagesPageCore_(a,{conversationId:p.conversationId,limit:p.limit||200}):{conversationId:"",messages:[],nextBeforeSeq:null};return{ok:true,conversations:conversations,chats:conversations,conversationId:messages.conversationId,messages:messages.messages,nextBeforeSeq:messages.nextBeforeSeq};}
function messageSend_(p){const a=auth_(p.sessionToken),cid=String(p.conversationId||p.chatId||""),text=cleanText_(p.text,4000),kind=String(p.kind||((p.mediaIds||[]).length?"file":"text"));if(!text&&!(p.mediaIds||[]).length)fail_("EMPTY_MESSAGE","Сообщение пустое");return locked_(()=>{const x=requireMember_(cid,a.userId);if(String(x.conversation.type)==="channel"&&!['owner','admin'].includes(String(x.member.role)))fail_("FORBIDDEN","Публиковать могут только администраторы");const seq=Number(x.conversation.last_message_seq||0)+1,at=now_(),messageId=id_("msg"),s=sheet_("MESSAGES",msgSheetName_(new Date()),HEADERS.Messages);const row={message_id:messageId,conversation_id:cid,seq:seq,sender_user_id:a.userId,kind:kind,text:text,reply_to_message_id:String(p.replyToMessageId||""),forwarded_from_message_id:String(p.forwardedFromMessageId||""),created_at:at,edited_at:"",deleted_at:"",expires_at:new Date(Date.now()+MESSAGE_TTL_MS).toISOString()};append_(s,row);patch_(sheet_("CONVERSATIONS","Conversations"),x.conversation._row,{last_message_seq:seq,last_message_at:at,updated_at:at});patch_(sheet_("CONVERSATIONS","ConversationMembers"),x.member._row,{last_read_seq:seq});const mediaSheet=sheet_("MESSAGES","MessageMedia");(p.mediaIds||[]).forEach(mid=>{const media=find_(mediaSheet,"media_id",mid,o=>!o.message_id&&!o.deleted_at);if(media)patch_(mediaSheet,media._row,{message_id:messageId,expires_at:row.expires_at});});return{ok:true,message:messagePublic_(row)};});}
function messageEdit_(p){const a=auth_(p.sessionToken),cid=String(p.conversationId||p.chatId||""),found=messageById_(cid,String(p.messageId));requireMember_(cid,a.userId);if(!found||String(found.row.sender_user_id)!==a.userId||String(found.row.kind)!=="text")fail_("FORBIDDEN","Изменять можно только своё текстовое сообщение");patch_(found.sheet,found.row._row,{text:cleanText_(p.text,4000),edited_at:now_()});return{ok:true};}
function messageDelete_(p){const a=auth_(p.sessionToken),cid=String(p.conversationId||p.chatId||""),found=messageById_(cid,String(p.messageId));requireMember_(cid,a.userId);if(!found||String(found.row.sender_user_id)!==a.userId)fail_("FORBIDDEN","Удалить можно только своё сообщение");patch_(found.sheet,found.row._row,{deleted_at:now_(),text:""});return{ok:true};}
function reactionToggle_(p){const a=auth_(p.sessionToken),cid=String(p.conversationId||p.chatId||""),mid=String(p.messageId),emoji=cleanText_(p.emoji,16);requireMember_(cid,a.userId);if(!messageById_(cid,mid))fail_("MESSAGE_NOT_FOUND","Сообщение не найдено");const s=sheet_("MESSAGES","MessageReactions"),r=find_(s,"message_id",mid,o=>String(o.conversation_id)===cid&&String(o.user_id)===a.userId&&String(o.emoji)===emoji);if(r)s.deleteRow(r._row);else append_(s,{conversation_id:cid,message_id:mid,user_id:a.userId,emoji:emoji,created_at:now_()});return{ok:true};}

function mediaRoot_(){const props=PropertiesService.getScriptProperties();let folderId=props.getProperty("MEDIA_ROOT_FOLDER_ID");if(!folderId){folderId=DriveApp.createFolder("Messenger Private Media").getId();props.setProperty("MEDIA_ROOT_FOLDER_ID",folderId);}return DriveApp.getFolderById(folderId);}
function mediaFolder_(uploadId){const parts=String(uploadId||"").split(".");if(parts.length!==2)fail_("INVALID_UPLOAD","Некорректная загрузка");const folder=DriveApp.getFolderById(parts[0]),meta=JSON.parse(folder.getDescription()||"{}");if(!constant_(sha_(parts[1]),String(meta.secretHash||"")))fail_("INVALID_UPLOAD","Некорректная загрузка");return{folder:folder,meta:meta};}
function mediaInit_(p){const a=auth_(p.sessionToken),cid=String(p.conversationId||p.chatId||"");requireMember_(cid,a.userId);const size=Number(p.sizeBytes||p.size)||0;if(size<0||size>MEDIA_MAX_BYTES)fail_("FILE_TOO_LARGE","Максимальный размер файла — 1 ГБ");const folder=mediaRoot_().createFolder(id_("upload")),secret=id_("secret"),meta={ownerUserId:a.userId,conversationId:cid,name:String(p.name||"file"),mimeType:String(p.mimeType||"application/octet-stream"),sizeBytes:size,sha256:String(p.sha256||""),chunkSize:MEDIA_CHUNK_BYTES,totalChunks:Math.ceil(size/MEDIA_CHUNK_BYTES),secretHash:sha_(secret),createdAt:now_()};folder.setDescription(JSON.stringify(meta));return{ok:true,uploadId:folder.getId()+"."+secret,chunkSizeBytes:MEDIA_CHUNK_BYTES,totalChunks:meta.totalChunks};}
function mediaPutChunk_(p){const a=auth_(p.sessionToken),u=mediaFolder_(p.uploadId);if(u.meta.ownerUserId!==a.userId)fail_("FORBIDDEN","Чужая загрузка");const index=Number(p.index);if(!Number.isInteger(index)||index<0||index>=u.meta.totalChunks)fail_("INVALID_CHUNK","Неверный номер части");const bytes=Utilities.base64Decode(String(p.dataBase64||""));if(bytes.length>MEDIA_CHUNK_BYTES)fail_("INVALID_CHUNK","Часть слишком большая");const expected=String(p.sha256||"");if(expected&&!constant_(expected,hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,bytes))))fail_("HASH_MISMATCH","Контрольная сумма части не совпала");const name="chunk_"+String(index).padStart(6,"0");const old=u.folder.getFilesByName(name);while(old.hasNext())old.next().setTrashed(true);u.folder.createFile(Utilities.newBlob(bytes,"application/octet-stream",name));return{ok:true,index:index};}
function mediaComplete_(p){const a=auth_(p.sessionToken),u=mediaFolder_(p.uploadId);if(u.meta.ownerUserId!==a.userId)fail_("FORBIDDEN","Чужая загрузка");let count=0,total=0,files=u.folder.getFiles();while(files.hasNext()){const f=files.next();if(/^chunk_\d{6}$/.test(f.getName())){count++;total+=f.getSize();}}if(count!==u.meta.totalChunks||total!==u.meta.sizeBytes)fail_("UPLOAD_INCOMPLETE","Получены не все части файла");const mediaId=id_("media"),at=now_();append_(sheet_("MESSAGES","MessageMedia"),{media_id:mediaId,message_id:"",storage_file_id:u.folder.getId(),original_name:u.meta.name,mime_type:u.meta.mimeType,size_bytes:u.meta.sizeBytes,sha256:u.meta.sha256,created_at:at,expires_at:new Date(Date.now()+MESSAGE_TTL_MS).toISOString(),deleted_at:""});return{ok:true,media:{mediaId:mediaId,name:u.meta.name,type:u.meta.mimeType,size:u.meta.sizeBytes,sha256:u.meta.sha256,totalChunks:u.meta.totalChunks,chunkSizeBytes:u.meta.chunkSize}};}
function mediaDownloadChunk_(p){const a=auth_(p.sessionToken),media=find_(sheet_("MESSAGES","MessageMedia"),"media_id",String(p.mediaId),o=>!o.deleted_at);if(!media)fail_("MEDIA_NOT_FOUND","Файл не найден");const folder=DriveApp.getFolderById(String(media.storage_file_id));if(media.message_id){let allowed=false;for(const s of candidateMessageSheets_()){const m=find_(s,"message_id",media.message_id);if(m){requireMember_(String(m.conversation_id),a.userId);allowed=true;break;}}if(!allowed)fail_("FORBIDDEN","Файл недоступен");}else{const meta=JSON.parse(folder.getDescription()||"{}");if(String(meta.ownerUserId)!==a.userId)fail_("FORBIDDEN","Файл недоступен");}const file=folder.getFilesByName("chunk_"+String(Number(p.index)).padStart(6,"0"));if(!file.hasNext())fail_("CHUNK_NOT_FOUND","Часть файла не найдена");const f=file.next(),bytes=f.getBlob().getBytes();return{ok:true,index:Number(p.index),dataBase64:Utilities.base64Encode(bytes),sha256:hex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,bytes))};}

function runDailyRetention(){const cutoff=Date.now(),mediaSheet=sheet_("MESSAGES","MessageMedia"),reactions=sheet_("MESSAGES","MessageReactions");candidateMessageSheets_().forEach(s=>objects_(s).forEach(m=>{if(!m.deleted_at&&m.expires_at&&new Date(m.expires_at).getTime()<=cutoff){patch_(s,m._row,{deleted_at:now_(),text:""});objects_(reactions).filter(r=>String(r.message_id)===String(m.message_id)).sort((a,b)=>b._row-a._row).forEach(r=>reactions.deleteRow(r._row));objects_(mediaSheet).filter(x=>String(x.message_id)===String(m.message_id)&&!x.deleted_at).forEach(x=>{try{DriveApp.getFolderById(String(x.storage_file_id)).setTrashed(true);}catch(e){}patch_(mediaSheet,x._row,{deleted_at:now_()});});}}));return{ok:true,finishedAt:now_()};}
